name: Continous Integration

on:
  push:
    branches:
      - staging 
      - release
jobs:
  buildcheck:
    name: Build and Test
    outputs:
      status: ${{ join(steps.*.conclusion) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          cache: 'npm'
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp-mail.outlook.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          to: johnsonlaizx@gmail.com
          from: jlaisg@outlook.com
