name: Continous Integration

on:
  push:
    branches:
      - staging 
      - release
      - master
jobs:
  buildcheck:
    name: Build and Test
    outputs:
      status: ${{ join(steps.*.conclusion) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          cache: 'npm'
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  cddeploy:
    name: Setup, Build, Publish, and Deploy
    needs: buildcheck
    if: !contains(needs.buildcheck.outputs.status, 'failure')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
